{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "c1d531a5_2212dfd8",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1293547
      },
      "writtenOn": "2021-02-05T03:54:49Z",
      "side": 1,
      "message": "Hello, please help me review this change. Thank you.",
      "revId": "fc66e980f9314b6b954f60758909728cddb706d4",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "e4f67b1e_c999120e",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1322146
      },
      "writtenOn": "2021-02-05T13:59:31Z",
      "side": 1,
      "message": "the CL itself has no problem, but to emphasize, that is important is to confirm if the data loss happens during reboot first.",
      "revId": "fc66e980f9314b6b954f60758909728cddb706d4",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}